nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'API Documentation for Sport Event Manager'
            version: '1.0.0'
    areas:
        default:
            path_patterns: ['^/api']
    models:
        names: []
