services:
    _defaults:
        autowire: true
        autoconfigure: true

    # This allows using the "@" symbol to reference services, and automatically handles autowiring
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Register annotation reader
    annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader

    # Sensio Framework Extra Bundle Annotations Configuration
    sensio_framework_extra.controller.listener:
        class: Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener
        arguments: ['@annotation_reader']

    sensio_framework_extra.cache.listener:
        class: Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener
        arguments: ['@annotation_reader']

    sensio_framework_extra.converter.listener:
        class: Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener
        arguments: ['@annotation_reader', '@sensio_framework_extra.converter.manager']

    sensio_framework_extra.security.listener:
        class: Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener
        arguments: ['@annotation_reader']

    sensio_framework_extra.view.listener:
        class: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener
        arguments: ['@annotation_reader']
